# NOTE - UPDATES SERVICES WITH DOCKER SYNC VOLUME!!!!
version: "2"
services:
  django:
    volumes:
      - django-sync:/code:nocopy

# Named volumes persist after their container is removed.
# When making changes to a service config (eg. mariadb) that uses "dbdata",
# or if mariadb becomes corrupted, remove the named volume and start fresh before bringing the stack up
volumes:
  # external since they're from docker-sync/unison containers
  django-sync:
    external: true
